const employees = [
  {
    id: 1,
    firstName: "Aarav",
    email: "employee1@example.com",
    password: "123",
    taskNumbers: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Prepare Report",
        description: "Prepare the monthly sales report",
        date: "2025-10-25",
        category: "Reporting",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Team Meeting",
        description: "Attend the weekly team meeting",
        date: "2025-10-20",
        category: "Meeting",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Update Client",
        description: "Send updated project status to client",
        date: "2025-10-24",
        category: "Client",
      },
    ],
  },
  {
    id: 2,
    firstName: "Vihaan",
    email: "employee2@example.com",
    password: "123",
    taskNumbers: {
      active: 3,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Code Review",
        description: "Review the code submitted by peers",
        date: "2025-10-26",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Database Backup",
        description: "Backup all production databases",
        date: "2025-10-21",
        category: "Maintenance",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Bug Fix",
        description: "Fix the critical bug in login module",
        date: "2025-10-23",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Deploy Update",
        description: "Deploy latest version to staging",
        date: "2025-10-25",
        category: "Deployment",
      },
    ],
  },
  {
    id: 3,
    firstName: "Ishaan",
    email: "employee3@example.com",
    password: "123",
    taskNumbers: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Customer Support",
        description: "Respond to customer queries",
        date: "2025-10-24",
        category: "Support",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Write Documentation",
        description: "Update API documentation",
        date: "2025-10-20",
        category: "Documentation",
      },
    ],
  },
  {
    id: 4,
    firstName: "Reyansh",
    email: "employee4@example.com",
    password: "123",
    taskNumbers: {
      active: 3,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Design UI",
        description: "Design the new dashboard interface",
        date: "2025-10-27",
        category: "Design",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Prototype Testing",
        description: "Test the new UI prototype",
        date: "2025-10-25",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Team Feedback",
        description: "Collect feedback from team members",
        date: "2025-10-22",
        category: "Meeting",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Update Assets",
        description: "Update icons and images in project",
        date: "2025-10-24",
        category: "Design",
      },
    ],
  },
  {
    id: 5,
    firstName: "Advait",
    email: "employee5@example.com",
    password: "123",
    taskNumbers: {
      active: 4,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Server Maintenance",
        description: "Perform routine server maintenance",
        date: "2025-10-26",
        category: "Maintenance",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Audit Logs",
        description: "Check audit logs for security issues",
        date: "2025-10-21",
        category: "Security",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Optimize Database",
        description: "Optimize queries and indexes",
        date: "2025-10-23",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Team Briefing",
        description: "Brief team about upcoming project",
        date: "2025-10-25",
        category: "Meeting",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Update Docs",
        description: "Update internal project documentation",
        date: "2025-10-24",
        category: "Documentation",
      },
    ],
  },
];



const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Oversee Projects",
        description: "Monitor all ongoing employee projects",
        date: "2025-10-25",
        category: "Management",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Approve Leaves",
        description: "Approve or reject employee leave requests",
        date: "2025-10-24",
        category: "HR",
      },
    ],
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
